### ISSUE TITLE
Explore UX checklist

### ISSUE THREAD

**Issue by julieguthrie** [nationalarchives/delivery-checklist#1]
## Explore UX checklist
Owned by UX team @jklepfer @bethmorr 

# STAGE ONE
- [ ] Desk research/competitor review
All of these steps start in Explore then are revisited in Alpha, Beta and Live
- [ ] Define Users/User group - TEAM
- [ ] Define the business case (and ensure work aligns with this) - PRODUCT OWNER/DELIVERY MANAGER
- [ ] Define hypothesis/product/service - TEAM
- [ ] Define User Goals - TEAM
- [ ] Define Current user journey (and potential user journey) incl pain points - UX and TEAM

# STAGE TWO
In all phases, Explore to Live
- [ ] Ensure research and design are inclusive (WCAG 2.1 guidelines) TEAM (UX led)
- [ ] Design research plan (methods, tasks etc ) - UX
- [ ] Consider any laws or policies that may apply (incl GDPR) TEAM
- [ ] Clarify and agree any objectives for user testing - TEAM
- [ ] Define metrics for testing - UX and TEAM
- [ ] Consider assisted digital - TEAM

# STAGE THREE
All phases Explore to Live
- [ ] Organise and plan practical elements of user research (recruitment/dates/equipment etc)- UX and TEAM
- [ ] Carry out User Testing UX (with team if available)

# STAGE FOUR
All phases Explore to Live
- [ ] Transcription of Data from research - UX
- [ ] Analysis of data - UX and ANALYTICS

# STAGE FIVE
All phases Explore to Live
- [ ] Prioritise User needs - TEAM (UX LED)
- [ ] Distribute/Discuss research findings - TEAM (UX LED)
- [ ] Document User Insights and create design artefacts such as user journeys, storyboards etc - UX

**ITERATE and REFINE!**

**Comment by jklepfer** [comment]
@bethmorr and @julieguthrie I have added desk research to the checklist for explore :)
