### ISSUE TITLE
Beta UX checklist

### ISSUE THREAD

**Issue by julieguthrie** [nationalarchives/delivery-checklist#13]
## Beta UX checklist
Owned by UX team @jklepfer @bethmorr 

- [ ] Document user insights (an create design artefacts such as user journeys, storyboards etc) - UX
- [ ] Distribute/discuss research findings - Team  (UX led)
- [ ] Priortise user needs - Team
- [ ] Ensure research & design are inclusive (accessible to all WCAG 2.1) - Team (UX led)
- [ ] Design research plan (e.g. methods, tasks, etc.) - UX
- [ ] Consider any laws/policies that may apply (e.g. data, GDPR etc.) - Team
- [ ] Define metrics for testing - Team
- [ ] Clarify and agree objectives for user research - Team
- [ ] Assisted digital?!
- [ ] Carry out user testing - UX team
- [ ] Organise & plan practical elements of user research (e.g. recruitment, dates, recording equipment etc.) - Team (UX led)
- [ ] Analysis of qualiitative & quantitaitive data - UX/GA
- [ ] Review and action feedback from survey, widget etc.
- [ ] Transcription of data from research - UX
