### ISSUE TITLE
*Beta BE dev checklist*

### ISSUE THREAD

**Issue by julieguthrie** [nationalarchives/delivery-checklist#23]
Owned by ACTNA
**Dev task list**
- [ ] 

**Pre-release checks**
- [ ] Release request is submitted to the Release Manager (AC, KK, AA) by Product Manager/Lead Developer
- [ ] Integration tests are executed and passed
- [ ] Features are tested and approved by Product Manager
- [ ] Submit Change Request on vFire
- [ ] Update Narnia
