### ISSUE TITLE
Explore metrics checklist

### ISSUE THREAD

**Issue by julieguthrie** [nationalarchives/delivery-checklist#3]
## Explore metrics checklist
Owned by @hoake 

- [ ] What do we currently know about usage and behaviours [Metrics and UX, Team]. What are they looking at, how did they get there, what did they interact with, did they see the feature? This may involve a number of different qualitive/quantative metrics, including but not exclusive to GA, surveys, UX research, business reports (refunds, digital downloads).
- [ ] Are there any gaps in our knowledge (this will add to what we need to track). What didn't we find out? [TEAM]
- [ ] Tracking outcomes based on user stories and business goals. Why are we doing this? Include UX and business goals. [TEAM]
- [ ] Identify key metrics for success [TEAM]
