### ISSUE TITLE
Explore communications checklist

### ISSUE THREAD

**Issue by julieguthrie** [nationalarchives/delivery-checklist#6]
## Explore communications checklist
Owned by Product Owners & Delivery Managers @sdwilkes @mcieslak @ACTNA @ruthroberts @julieguthrie 

- [ ] roadmap distributed across business
- [ ] establish stakeholders
- [ ] where relevant, approval process agreed and buy-in received from stakeholders
- [ ] establish who we need for the alpha phase
- [ ] create plan, timeline, availability of team, meetings etc.
- [ ] if relevant discuss what to name proposed service
- [ ] decide whether the feature is a go or no go into alpha
- [ ] where relevant, get approval for go/no go from appropriate channel e.g. discovery board, exec team, UAG, DESG
