### ISSUE TITLE
Alpha UX checklist

### ISSUE THREAD

**Issue by julieguthrie** [nationalarchives/delivery-checklist#8]
## Alpha UX Checklist
Owned by UX team @jklepfer @bethmorr 

- [ ] Document user insights (an create design artefacts such as user journeys, storyboards etc) - UX team
- [ ] Distribute/discuss research findings - Team  (UX led)
- [ ] Priortise user needs - Team
- [ ] Create user stories (in alpha) - Team
- [ ] Create user stories based on research - Team
- [ ] Prioritise user stories - Team
- [ ] Creation of acceptance criteria - Team (PO led)
- [ ] Test iteratively until team/users/acceptance criteria met
- [ ] Ensure research & design are inclusive (accessible to all WCAG 2.1) - Team (UX led)
- [ ] Design research plan (e.g. methods, tasks, etc.) - UX
- [ ] Consider any laws/policies that may apply (e.g. data, GDPR etc.) - Team
- [ ] Define metrics for testing - Team
- [ ] Clarify and agree objectives for user research - Team
- [ ] Assisted digital?
- [ ] User testing - UX
- [ ] Organise & plan practical elements of user research (e.g. recruitment, dates, recording equipment etc.) - Team (UX led)
- [ ] Analysis of qualitative & quantitative data - UX/GA
- [ ] Transcription of data from research - UX
