### ISSUE TITLE
Alpha metrics checklist

### ISSUE THREAD

**Issue by julieguthrie** [nationalarchives/delivery-checklist#9]
## Alpha metrics checklist
Owned by @hoake 

- [ ] Identify backend and front end and or GTM development with desired outcomes. Issues need to be raised for development in tna-google-tag-manager-scripts repository and referencing theme and discovery repos. [METRICS and DEVELOPERS]
- [ ] Each issue will state requirements for development and testing checklist. https://github.com/nationalarchives/tna-google-tag-manager-scripts/projects/1 [METRICS and DEVELOPERS]
- [ ] Testing checklist using GTM preview [METRICS and DEVELOPERS]
